test:
  domain: localhost

development:
  domain: "localhost:3000"

production:
  domain: 119.90.15.157
  # whether this instance of canvas is served over ssl (https) or not
  # defaults to true for production, false for test/development
  ssl: false
  # files_domain: "canvasfiles.example.com"
