development:
  address: "smtp.163.com"
  port: "25"
  user_name: "dev_admin@163.com"
  password: "1qaz2wsx"
  authentication: "plain" # plain, login, or cram_md5
  domain: "www.163.com"
  outgoing_address: "dev_admin@163.com"
  default_name: "mr chen"

# or to use sendmail --
#
# development:
#   delivery_method: "sendmail"

test:
  delivery_method: "test"

production:
  address: "smtp.163.com"
  port: "25"
  user_name: "dev_admin@163.com"
  password: "1qaz2wsx"
  authentication: "plain" # plain, login, or cram_md5
  domain: "www.163.com"
  outgoing_address: "dev_admin@163.com"
  default_name: "mr chen"

# If receiving mail from multiple inboxes (see incoming_mail.yml.example),
# you'll want to include those addresses in a reply_to_addresses array so
# Canvas will select the Reply-To field of outgoing messages from all of the
# incoming mailboxes.

multiple_inboxes:
  address: "smtp.163.com"
  port: "25"
  user_name: "dev_admin@163.com"
  password: "1qaz2wsx"
  authentication: "plain" # plain, login, or cram_md5
  domain: "www.163.com"
  outgoing_address: "dev_admin@163.com"
  default_name: "mr chen"
  reply_to_addresses:
  - "dev_test01@163.com"
  - "dev_test02@163.com"
  - "dev_test03@163.com"
  - "dev_test04@163.com"

