---
production:
  encryption_key: !binary |-
    YjExMDJlODlmY2ZjNGJkMzMzMDRhODNlMmI0NzY1MTk4NjkxOGEzMzdjM2Qx
    ZWViOGUwMmI2NTNhODNkNjAxNGJiZGQ0YWFmOTdkOGNlNWQwNTE4YWUyNmRl
    MTQ3NDQ5NTZiODIxOWY1NjRiM2RhZWQyYzRkYWYwNzBlNzgyM2M=
development:
  encryption_key: facdd3a131ddd8988b14f6e4e01039c93cfa0160
test:
  encryption_key: facdd3a131ddd8988b14f6e4e01039c93cfa0160
