---
production:
  encryption_key: !binary |-
    Yzc1YjE4ODI1MzM1M2FiNDA3NDM1NjY3YWMzNDkxNGIwZjU3MzcwNDZhNjMw
    NjgyNjkzYzRmNzVlMTA0ZDQ2NjZlNzdkMjkzNTE0MGZhNjc3MWJiZGZiMGE3
    Y2VjZDI4NWQ0YzYyYjBmYjdiYzY4NzY5N2VkN2Q5MGZjNzIyMzg=
development:
  encryption_key: facdd3a131ddd8988b14f6e4e01039c93cfa0160
test:
  encryption_key: facdd3a131ddd8988b14f6e4e01039c93cfa0160
